From b9bdf241f107905534920a60aeaad44434aa27ca Mon Sep 17 00:00:00 2001
From: Mike Gilbert <floppym@gentoo.org>
Date: Fri, 3 Apr 2020 10:37:56 -0400
Subject: [PATCH 11/22] test.support.unlink: ignore PermissionError

Resolves test errors when running in the Gentoo sandbox environment.

Bug: https://bugs.gentoo.org/679628
---
 Lib/test/support/__init__.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Lib/test/support/__init__.py b/Lib/test/support/__init__.py
index fb09e0623e..ab76056f64 100644
--- a/Lib/test/support/__init__.py
+++ b/Lib/test/support/__init__.py
@@ -444,7 +444,7 @@ else:
 def unlink(filename):
     try:
         _unlink(filename)
-    except (FileNotFoundError, NotADirectoryError):
+    except (FileNotFoundError, NotADirectoryError, PermissionError):
         pass
 
 def rmdir(dirname):
-- 
2.35.1

