From b86a86773a7c49cad26df64493f4cb818c9e3272 Mon Sep 17 00:00:00 2001
From: Mike Gilbert <floppym@gentoo.org>
Date: Fri, 5 Jan 2018 13:32:45 -0500
Subject: [PATCH 03/12] setup.py: exit with non-zero status on failure

https://bugs.gentoo.org/show_bug.cgi?id=281968
https://bugs.python.org/issue6731
---
 setup.py | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/setup.py b/setup.py
index 6c77c17bb0..252a27993b 100644
--- a/setup.py
+++ b/setup.py
@@ -129,6 +129,7 @@ def get_platform():
 Topic :: Software Development
 """
 
+exit_status = 0
 
 def run_command(cmd):
     status = os.system(cmd)
@@ -561,8 +562,10 @@ def print_three_column(lst):
             print("been built, they are *disabled* by configure:")
             print_three_column(self.disabled_configure)
             print()
+        global exit_status
 
         if self.failed:
+            exit_status = 1
             failed = self.failed[:]
             print()
             print("Failed to build these modules:")
@@ -570,6 +573,7 @@ def print_three_column(lst):
             print()
 
         if self.failed_on_import:
+            exit_status = 1
             failed = self.failed_on_import[:]
             print()
             print("Following modules built successfully"
@@ -2757,6 +2761,7 @@ class DummyProcess:
           scripts = ["Tools/scripts/pydoc3", "Tools/scripts/idle3",
                      "Tools/scripts/2to3"]
         )
+    sys.exit(exit_status)
 
 # --install-platlib
 if __name__ == '__main__':
-- 
2.35.1

